server:
  servlet:
    context-path: /
  port: 23333

spring:
  application:
    name: minimalism
  servlet:
    multipart:
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://localhost:3306/MINIMALISM?useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: 1qaz@WSX
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 3
      driver-class-name: com.mysql.jdbc.Driver
      validation-query: SELECT 1
      stat-view-servlet:
        allow: 127.0.0.1
      test-while-idle: true
      test-on-return: false
      filters: stat,wall

  redis:
    timeout: 10s
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    port: 6379
    host: localhost


# jdbc
pagehelper:
  helper-dialect: mysql
  params: count\=countSql
  reasonable: true
  support-methods-arguments: true


swagger:
  basic:
    password: jokee233
    enable: true

logging:
  file:
    max-history: 10
    max-size: 128MB
    path: ./logs/minimalism.log
  level:
    com:
      jk: debug


token:
  jwt-secret: (JI\:)_$^11244^%$_(JIAN\:)_@@++--(ZHU\:)_++++_.sds_(YI\:)
  expire:
    seconds: 129600
mybatis:
  mapper-locations: classpath\:/mybatis-mappers/*
  type-aliases-package: com.jk.minimalism.bean.entity

minimalism:
  enable-swagger: true
  debug: true